[package]
name = "noise"
description = "Procedural noise generation library."
homepage = "https://github.com/bjz/noise-rs"
repository = "https://github.com/bjz/noise-rs"
version = "0.2.0"
license = "Apache-2.0"
keywords = ["math", "random"]
authors = ["The Noise-rs Developers."]

[lib]
name = "noise"

[[example]]
name = "perlin"

[[example]]
name = "open_simplex"

[[example]]
name = "wavelet"

[[example]]
name = "brownian"

[[example]]
name = "cell_range"

[[example]]
name = "cell_range_inv"

[[example]]
name = "cell_value"

[[example]]
name = "cell_manhattan"

[[example]]
name = "cell_manhattan_inv"

[[example]]
name = "cell_manhattan_value"

[[bench]]
name = "benches"

[dependencies]
rand = "0.3"
num = "0.1"

[dev-dependencies]
image = "0.7"
